// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sqlflow.proto

package sqlflow

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SQL statements to be executed
// e.g.
//      1. `USE database`
//      2. `SELECT ...`
//      3. `SELECT ... TRAIN/PREDICT ...`
type RunRequest struct {
	Sql                  string   `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunRequest) Reset()         { *m = RunRequest{} }
func (m *RunRequest) String() string { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()    {}
func (*RunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e9f9b081a5698ac, []int{0}
}

func (m *RunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest.Unmarshal(m, b)
}
func (m *RunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest.Marshal(b, m, deterministic)
}
func (m *RunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest.Merge(m, src)
}
func (m *RunRequest) XXX_Size() int {
	return xxx_messageInfo_RunRequest.Size(m)
}
func (m *RunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest proto.InternalMessageInfo

func (m *RunRequest) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

// SQL statements like `USE database` returns only a success message.
// In such cases, the return stream contains only one RunResponse with
// RunResponse.message set.
//
// SQL statements like `SELECT ...` returns a table in addition
// to the status, and the table might be big.  In such cases, Run returns a
// stream of RunResponse
//
// SQL statement like `SELECT ... TRAIN/PREDICT ...` returns a stream of message
// which indicates the training/predicting progress
//
// Each RunResponse doesn't exceed the maximum message size
// (https://stackoverflow.com/a/34186672/724872).
type RunResponse struct {
	Message              []string           `protobuf:"bytes,1,rep,name=message,proto3" json:"message,omitempty"`
	Columns              map[string]*Column `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RunResponse) Reset()         { *m = RunResponse{} }
func (m *RunResponse) String() string { return proto.CompactTextString(m) }
func (*RunResponse) ProtoMessage()    {}
func (*RunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e9f9b081a5698ac, []int{1}
}

func (m *RunResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunResponse.Unmarshal(m, b)
}
func (m *RunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunResponse.Marshal(b, m, deterministic)
}
func (m *RunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunResponse.Merge(m, src)
}
func (m *RunResponse) XXX_Size() int {
	return xxx_messageInfo_RunResponse.Size(m)
}
func (m *RunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunResponse proto.InternalMessageInfo

func (m *RunResponse) GetMessage() []string {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *RunResponse) GetColumns() map[string]*Column {
	if m != nil {
		return m.Columns
	}
	return nil
}

// A data column of any type
type Column struct {
	Data                 []*any.Any `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}
func (*Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e9f9b081a5698ac, []int{2}
}

func (m *Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Column.Unmarshal(m, b)
}
func (m *Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Column.Marshal(b, m, deterministic)
}
func (m *Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Column.Merge(m, src)
}
func (m *Column) XXX_Size() int {
	return xxx_messageInfo_Column.Size(m)
}
func (m *Column) XXX_DiscardUnknown() {
	xxx_messageInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_Column proto.InternalMessageInfo

func (m *Column) GetData() []*any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RunRequest)(nil), "sqlflow.RunRequest")
	proto.RegisterType((*RunResponse)(nil), "sqlflow.RunResponse")
	proto.RegisterMapType((map[string]*Column)(nil), "sqlflow.RunResponse.ColumnsEntry")
	proto.RegisterType((*Column)(nil), "sqlflow.Column")
}

func init() { proto.RegisterFile("sqlflow.proto", fileDescriptor_6e9f9b081a5698ac) }

var fileDescriptor_6e9f9b081a5698ac = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xc9, 0xae, 0x76, 0xe9, 0xac, 0xa2, 0xc4, 0x1e, 0xd6, 0x3d, 0xc8, 0xba, 0x20, 0xe4,
	0x94, 0x4a, 0xbc, 0x88, 0xe2, 0x41, 0x44, 0x2f, 0x7a, 0x31, 0xfe, 0x82, 0x54, 0xd3, 0x3d, 0x34,
	0x4d, 0xba, 0xcd, 0xc6, 0x92, 0x9f, 0xe5, 0x3f, 0x94, 0x26, 0x46, 0x2a, 0x78, 0xcb, 0xcc, 0xbc,
	0xf7, 0xf8, 0xf2, 0xe0, 0xd0, 0xf6, 0x6a, 0xae, 0xcc, 0x86, 0xae, 0xd6, 0x66, 0x30, 0xb8, 0xf8,
	0x19, 0xeb, 0xd3, 0xce, 0x98, 0x4e, 0xc9, 0x69, 0x58, 0xcf, 0xdc, 0x7c, 0x2a, 0xb4, 0x8f, 0x9a,
	0xf6, 0x0c, 0x80, 0x3b, 0xcd, 0x65, 0xef, 0xa4, 0x1d, 0xf0, 0x31, 0xe4, 0xb6, 0x57, 0x15, 0x6a,
	0x10, 0x19, 0xf3, 0xed, 0xb3, 0xfd, 0x42, 0x50, 0x06, 0x81, 0x5d, 0x19, 0x6d, 0x25, 0xae, 0xa0,
	0x58, 0x4a, 0x6b, 0x45, 0x27, 0x2b, 0xd4, 0xe4, 0x64, 0xcc, 0xd3, 0x88, 0x6f, 0xa1, 0x78, 0x37,
	0xca, 0x2d, 0xb5, 0xad, 0xb2, 0x26, 0x27, 0x25, 0x3b, 0xa7, 0x09, 0x67, 0x27, 0x80, 0x3e, 0x44,
	0xcd, 0xa3, 0x1e, 0xd6, 0x9e, 0x27, 0x47, 0xfd, 0x0c, 0x07, 0xbb, 0x87, 0x2d, 0xc8, 0x42, 0xfa,
	0x04, 0xb2, 0x90, 0x1e, 0x5f, 0xc0, 0xfe, 0xa7, 0x50, 0x4e, 0x56, 0x59, 0x83, 0x48, 0xc9, 0x8e,
	0x7e, 0xc3, 0xa3, 0x8f, 0xc7, 0xeb, 0x4d, 0x76, 0x8d, 0x5a, 0x06, 0xa3, 0xb8, 0xc4, 0x04, 0xf6,
	0x3e, 0xc4, 0x20, 0x02, 0x6a, 0xc9, 0x26, 0x34, 0xf6, 0x40, 0x53, 0x0f, 0xf4, 0x5e, 0x7b, 0x1e,
	0x14, 0xec, 0x0e, 0x8a, 0xb7, 0xd7, 0x97, 0x27, 0x65, 0x36, 0x98, 0x41, 0xce, 0x9d, 0xc6, 0x27,
	0x7f, 0xf1, 0x43, 0x41, 0xf5, 0xe4, 0xbf, 0x3f, 0x5d, 0xa2, 0xd9, 0x28, 0x44, 0x5e, 0x7d, 0x07,
	0x00, 0x00, 0xff, 0xff, 0xe4, 0xec, 0x9a, 0xa3, 0x82, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SQLFlowClient is the client API for SQLFlow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SQLFlowClient interface {
	// Run runs a SQL statement and returns a stream of RunResponse.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (SQLFlow_RunClient, error)
}

type sQLFlowClient struct {
	cc *grpc.ClientConn
}

func NewSQLFlowClient(cc *grpc.ClientConn) SQLFlowClient {
	return &sQLFlowClient{cc}
}

func (c *sQLFlowClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (SQLFlow_RunClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SQLFlow_serviceDesc.Streams[0], "/sqlflow.SQLFlow/Run", opts...)
	if err != nil {
		return nil, err
	}
	x := &sQLFlowRunClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SQLFlow_RunClient interface {
	Recv() (*RunResponse, error)
	grpc.ClientStream
}

type sQLFlowRunClient struct {
	grpc.ClientStream
}

func (x *sQLFlowRunClient) Recv() (*RunResponse, error) {
	m := new(RunResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SQLFlowServer is the server API for SQLFlow service.
type SQLFlowServer interface {
	// Run runs a SQL statement and returns a stream of RunResponse.
	Run(*RunRequest, SQLFlow_RunServer) error
}

func RegisterSQLFlowServer(s *grpc.Server, srv SQLFlowServer) {
	s.RegisterService(&_SQLFlow_serviceDesc, srv)
}

func _SQLFlow_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SQLFlowServer).Run(m, &sQLFlowRunServer{stream})
}

type SQLFlow_RunServer interface {
	Send(*RunResponse) error
	grpc.ServerStream
}

type sQLFlowRunServer struct {
	grpc.ServerStream
}

func (x *sQLFlowRunServer) Send(m *RunResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _SQLFlow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sqlflow.SQLFlow",
	HandlerType: (*SQLFlowServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _SQLFlow_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sqlflow.proto",
}
